import { Router } from 'express';
import { config } from '../config.js';

const REPORT_MAX = config.reportMaxRows;

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function sanitize(str, maxLen = 500) {
  if (typeof str !== 'string') return '';
  return escapeHtml(str).slice(0, maxLen);
}

export const reportRouter = Router();

reportRouter.post('/html', (req, res) => {
  const {
    reportName = 'Report',
    description = '',
    columns = [],
    rows = [],
    chartSvgs = [],
    mapSvg = null,
  } = req.body || {};

  if (!Array.isArray(columns) || !Array.isArray(rows)) {
    return res.status(400).json({ success: false, error: 'columns and rows required' });
  }

  const colNames = columns.map(c => (typeof c === 'object' && c?.name) || String(c));
  const limitedRows = rows.slice(0, REPORT_MAX);

  const tableRows = limitedRows
    .map(
      row =>
        `<tr>${colNames.map((_, i) => `<td>${escapeHtml(String(row[i] ?? ''))}</td>`).join('')}</tr>`
    )
    .join('');

  const thead = `<thead><tr>${colNames.map(c => `<th>${escapeHtml(String(c))}</th>`).join('')}</tr></thead>`;
  const chartBlocks = (chartSvgs || [])
    .map(svg => (svg ? `<div class="chart">${svg}</div>` : ''))
    .filter(Boolean)
    .join('');
  const mapBlock = mapSvg ? `<div class="report-map-wrap"><div class="report-map-inner">${mapSvg}</div></div>` : '';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${sanitize(reportName, 200)}</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" crossorigin="" />
  <style>
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
    body { font-family: system-ui, sans-serif; margin: 1rem; color: #222; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .description { margin-bottom: 1rem; color: #555; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.85rem; }
    th, td { border: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left; }
    th { background: #f0f0f0; }
    .chart, .report-map-wrap { margin: 1.5rem 0; page-break-inside: avoid; }
    .chart svg { max-width: 100%; height: auto; }
    /* Map snapshot: give container size so Leaflet panes and tiles are visible */
    .report-map-wrap { position: relative; width: 100%; min-height: 400px; overflow: hidden; border: 1px solid #ccc; background: #e4e4e4; }
    .report-map-inner { position: relative; width: 100%; height: 400px; }
    .report-map-inner .leaflet-map-pane { position: absolute !important; left: 0 !important; top: 0 !important; right: 0 !important; bottom: 0 !important; width: 100% !important; height: 100% !important; visibility: visible !important; opacity: 1 !important; }
    .report-map-inner .leaflet-tile-pane { visibility: visible !important; opacity: 1 !important; z-index: 1; }
    .report-map-inner .leaflet-tile-pane img { visibility: visible !important; opacity: 1 !important; mix-blend-mode: normal !important; }
    .report-map-inner .leaflet-overlay-pane { visibility: visible !important; opacity: 1 !important; z-index: 2; }
    .report-map-inner .leaflet-overlay-pane svg { visibility: visible !important; opacity: 1 !important; max-width: none !important; max-height: none !important; }
    .report-map-inner .leaflet-marker-pane { visibility: visible !important; opacity: 1 !important; z-index: 3; }
    .report-map-inner img.leaflet-tile { max-width: none !important; max-height: none !important; visibility: visible !important; opacity: 1 !important; }
    /* Minimal Leaflet pane layout if CDN CSS fails */
    .report-map-inner .leaflet-pane { position: absolute; left: 0; top: 0; }
    .report-map-inner .leaflet-tile { pointer-events: none; }
    .report-map-inner .leaflet-tile-pane { z-index: 1; }
    .report-map-inner .leaflet-overlay-pane { z-index: 2; }
    .report-map-inner .leaflet-marker-pane { z-index: 3; }
    @page { size: A4 landscape; margin: 1.5cm; }
  </style>
</head>
<body>
  <h1>${sanitize(reportName, 200)}</h1>
  ${description ? `<div class="description">${sanitize(description, 2000)}</div>` : ''}
  ${chartBlocks}
  ${mapBlock}
  <table>
    ${thead}
    <tbody>${tableRows}</tbody>
  </table>
  <p style="font-size: 0.8rem; color: #666;">Rows: ${limitedRows.length}${rows.length > REPORT_MAX ? ` (showing first ${REPORT_MAX})` : ''}. Generated by IoT Query Probe.</p>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Content-Disposition', 'inline; filename="report.html"');
  res.send(html);

  auditLog('report_html', { userId: req.user?.userId, rowCount: limitedRows.length });
});
